export const industries = [
    "Advertising agency",
    "Airline",
    "Airport shuttle service",
    "Amusement park",
    "Antique store",
    "Appliance repair service",
    "Aquarium",
    "Arcade",
    "Art gallery",
    "Attorney",
    "Bagel shop",
    "Bakery ",
    "Bar",
    "Barber shop",
    "Bike shop",
    "Beauty supply store",
    "Bed and breakfast ",
    "Bike rental service",
    "Boat rental service",
    "Bookstore",
    "Bowling alley",
    "Brewery",
    "Bubble tea shop",
    "Burger restaurant",
    "Camping equipment store",
    "Candy store",
    "Car dealership ",
    "Car detailing service",
    "Car rental agency",
    "Car wash",
    "Catering service",
    "CC ",
    "CCC ",
    "Cell phone repair service",
    "Cleaning service",
    "Clothing store",
    "Coffee shop ",
    "Comedy club",
    "Computer repair shop ",
    "Consignment shop",
    "Consulting firm",
    "Convenience store",
    "Craft store",
    "Dance studio",
    "Day spa ",
    "Daycare center",
    "Dental office ",
    "Donut shop",
    "Dry cleaning service ",
    "Electrical contractor ",
    "Electronics store",
    "Engineering firm ",
    "Escape room",
    "Event planning company ",
    "Farmers market",
    "Fashion boutique ",
    "Fast food restaurant",
    "Financial advisor ",
    "Fitness apparel store",
    "Fitness center ",
    "Florist",
    "Food truck",
    "Frozen yogurt shop",
    "Furniture store",
    "Gas station",
    "General contractor",
    "GG ",
    "Gift shop",
    "Golf course ",
    "Graphic design firm",
    "Graphic design studio ",
    "Grocery delivery service",
    "Grocery store ",
    "Hair salon ",
    "Hardware store",
    "HH ",
    "HHH ",
    "Home cleaning service ",
    "Home renovation company",
    "Home security company",
    "Hostel",
    "Hotel",
    "Hunting and fishing store",
    "HVAC contractor",
    "Ice cream shop",
    "II ",
    "Insurance agency ",
    "Interior design firm ",
    "Investment firm ",
    "IT services company",
    "Jewelry store ",
    "JJJ ",
    "Juice bar ",
    "Junk removal service ",
    "K ",
    "Karaoke bar ",
    "KK ",
    "KKK ",
    "Landscape design firm",
    "Landscape service ",
    "Language school",
    "Laundromat",
    "Law firm ",
    "Lawn care service",
    "Limousine service ",
    "Locksmith",
    "Marketing agency ",
    "Massage therapist ",
    "MM ",
    "Movie rental store",
    "Movie theater",
    "Moving company",
    "Museum",
    "Music lessons provider",
    "Music store ",
    "Nail salon ",
    "Nightclub",
    "NN ",
    "Non - profit organization ",
    "Office supply store",
    "OO ",
    "Optometrist office ",
    "Organic food store ",
    "Outdoor gear store",
    "Painting contractor",
    "Pest control service",
    "Pet store ",
    "Pharmacy",
    "Pharmacy ",
    "Photography studio",
    "Pilates studio",
    "Pizza restaurant",
    "Plumbing company",
    "Popcorn shop",
    "Printing company",
    "QQ ",
    "Quick print shop ",
    "Real estate agency ",
    "Record store",
    "Restaurant ",
    "Roofing contractor",
    "Sandwich shop",
    "Scooter rental service",
    "Senior care facility",
    "Shoe repair shop",
    "Shoe store",
    "Ski and snowboard shop",
    "Smoothie bar",
    "Social media marketing agency ",
    "Software company ",
    "Spa",
    "Specialty food store",
    "Sporting goods store",
    "Sports bar",
    "Tailor",
    "Tanning salon ",
    "Taxi service",
    "Thrift store",
    "Toy store",
    "Travel agency ",
    "Uniform store ",
    "Used book store ",
    "Veterinary clinic ",
    "Video game store",
    "Vintage clothing store ",
    "Water park",
    "Web development company ",
    "Wedding planning service",
    "Wine bar ",
    "Wine store",
];